force-app/main/default/objects/Student__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <description>getting Grade depends on Score</description>
    <formula>IF(Score__c &gt;= 90, &quot;A&quot;,
  IF(Score__c &gt;= 80, &quot;B&quot;,
    IF(Score__c &gt;= 70, &quot;C&quot;,
      IF(Score__c &gt;= 60, &quot;D&quot;, &quot;F&quot;)
    )
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grade</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StudentController.cls
public with sharing class StudentController {
  public static List<Student__c> getStudents() {
    List<Student__c> students = [
      SELECT Name, Score__c, Grade__c
      FROM Student__c
      ORDER BY Score__c DESC
    ];
    return students;
  }

  public static List<Student__c> getTopStudents(Integer n) {
    List<Student__c> students = [
      SELECT Name, Score__c, Grade__c
      FROM Student__c
      ORDER BY Score__c DESC
      LIMIT :n
    ];
    return students;
  }
}