force-app/main/default/objects/Task__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TaskController.cls
public with sharing class TaskController {
    @AuraEnabled(cacheable=true)
    public static List<Task__c> getTasks(String userId) {
        return [SELECT Id, Name, Subject__c, Done__c, DueDate__c FROM  Task__c WHERE OwnerId = :userId];
    }
    
    @AuraEnabled
    public static void markDone(Id taskId){
        Task__c task =  [
            SELECT Id, Name, Subject__c, Done__c, DueDate__c 
            FROM  Task__c 
            WHERE Id = :taskId
        ];
        task.Done__c =  !task.Done__c;
        update task;
    }
}